version: "3.9"

services:
  postgres-ecom:
    image: ankane/pgvector
    container_name: postgres-ecom
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phuc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb-ecom:
    image: mongodb/mongodb-community-server:7.0.5-ubi8
    container_name: mongodb-ecom
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - mongodb-data:/data/db
    networks:
      - phuc-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
    command:
      [
        "redis-server",
        "--requirepass", "",
        "--appendonly", "yes",
        "--appendfsync", "always",
        "--save", "900", "1",
        "--save", "300", "10",
        "--save", "60", "10000"
      ]
    volumes:
      - redis-data:/data
    networks:
      - phuc-network

volumes:
  mongodb-data:
    driver: local
  postgres_data:
    driver: local
  redis-data:
    driver: local
networks:
  phuc-network:
    driver: bridge




