version: "3.9"

services:
  postgres-ecom:
    image: ankane/pgvector
    container_name: postgres-ecom
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=e-comerce
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - phuc-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb-ecom:
    image: mongodb/mongodb-community-server:7.0.5-ubi8
    container_name: mongodb-ecom
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - mongodb-data:/data/db
    networks:
      - phuc-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=123456
    command:
      [
        "redis-server",
        "--requirepass", "123456",
        "--appendonly", "yes",
        "--appendfsync", "always",
        "--save", "900", "1",
        "--save", "300", "10",
        "--save", "60", "10000"
      ]
    volumes:
      - redis-data:/data
    networks:
      - phuc-network


  kafka:
    image: confluentinc/cp-kafka:latest-ubi9
    container_name: kafka
    hostname: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - phuc-network

volumes:
  mongodb-data:
    driver: local
  postgres_data:
    driver: local
  redis-data:
    driver: local
networks:
  phuc-network:
    driver: bridge




