server:
  port: ${PROMOTION_SERVICE_PORT:8097}
  servlet:
    context-path: /promotion
spring:
  application:
    name: promotion-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongodb}:${MONGO_PASSWORD:123456}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${PROMOTION_SERVICE_DB:PromotionService}?authSource=admin

  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}


