server:
  port: ${PRODUCT_SERVICE_PORT:8091}
  servlet:
    context-path: /product

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongodb}:${MONGO_PASSWORD:123456}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${PRODUCT_SERVICE_DB:ProductService}?authSource=admin


  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}

shop:
  service:
    url: ${SHOP_SERVICE_URL}

file:
  service:
    url: ${FILE_SERVICE_URL}

order:
  service:
    url: ${ORDER_SERVICE_URL}
