server:
  port: ${REVIEW_SERVICE_PORT:8097}
  servlet:
    context-path: /review

#  data:
#    mongodb:
#      uri: mongodb://${MONGO_USERNAME:mongodb}:${MONGO_PASSWORD:123456}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${REVIEW_SERVICE_DB:ReviewService}?authSource=admin

spring:
  application:
    name: review-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${REVIEW_SERVICE_DB:ReviewService}
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}


